config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|sk/ do
    get 'login/new'
    get 'quests/index'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    post   '/sign_up',        to: 'sign_up#create'
    get    '/login',          to: 'login#new'
    post   '/login',          to: 'login#create'
    delete '/login',          to: 'login#logout'
    delete '/logout',         to: 'login#destroy'
    get    '/quests',         to: 'quests#index'
    patch  '/quests',         to: 'quests#complete'
    post   '/quests',         to: 'quests#complete'
    delete '/quests',         to: 'quests#delete'
    get    '/allquests',      to: 'allquests#index'
    post   '/allquests',      to: 'allquests#new'
    put    '/allquests',      to: 'allquests#add_to_room'
    get    '/quest_detail',   to: 'quest_detail#index'
    get    '/created_quests', to: 'created_quests#index'
    delete '/created_quests', to: 'created_quests#delete'
    post   '/created_quests', to: 'created_quests#index'
    delete '/new_quests',     to: 'new_quests#delete'
    get    '/new_quests',     to: 'new_quests#index'
    post   '/new_quests',     to: 'new_quests#new'
    get    '/rooms',          to: 'rooms#index'
    get    '/room_detail',    to: 'room_detail#index'
    post   '/room_detail',    to: 'room_detail#join'
    patch  '/room_detail',    to: 'room_detail#leave'
    delete '/room_detail',    to: 'room_detail#delete'
    get    '/create_room',    to: 'create_room#index'
    get    '/admin_rooms',    to: 'admin_rooms#index'
    put    '/admin_rooms',    to: 'admin_rooms#add_to_room'
    get    '/home',           to: 'home#index'
    patch  '/home',           to: 'home#change_locale'
    get    '/about',          to: 'about#index'
    get    '/create_quest',   to: 'create_quest#index'
    get    '/users',          to: 'users#index'
    put    '/users',          to: 'users#make_admin'
    get    '/index',          to: 'index#index'

    resources :quests do
        post :accept
        delete :delete
      end

    resources :users
    resources :create_quest
    resources :index
    resources :login
    resources :sign_up
    resources :home
    resources :quest_detail
    resources :created_quests
    resources :new_quests
    resources :rooms
    resources :room_detail
    resources :create_room
    resources :allquests do
      post :accept
    end
    root 'home#index'

  end


end

app/models/quest.rb
class Quest < ApplicationRecord
  has_many :users_quests
  has_many :users, through: :users_quests
  has_many :rooms_quests
  has_many :rooms, through: :rooms_quests

  def accept (user)
    usersQuest = UsersQuest.new(user_id: user.id,
                                quest_id: self.id, status: 1)
    usersQuest.save!
  end

  def delete_quest
    self.users_quests.delete_all
    self.rooms_quests.delete_all
    self.delete
  end
  def complete(user)
    correct = true
    user.addScore(self.reward)
    unless user.save!
      raise ActiveRecord::Rollback, "adding score failed"
      correct = false
    end
    connection = UsersQuest.where(user_id: user.id, quest_id: self.id, status: 1).first
    if connection && connection.status.eql?(1)
      connection.status = 2
      unless connection.save!
        raise ActiveRecord::Rollback, "completing save failed"
        correct = false
      end
    else
      false
    end
    correct
  end

  def give_up(user)
    UsersQuest.where(user_id: user.id, quest_id: self.id, status: 1).delete_all
  end

  def author
    self.users.where(users_quests: { status: 0 }).first
  end

  def set_author(user)
    users_quest = UsersQuest.new(user_id: user.id,
                                 quest_id: self.id,
                                 status: 0)
    users_quest.save!
  end

  def add_to_user user
    users_quest = UsersQuest.new(user_id: user.id,
                                 quest_id: self.id,
                                 status: 1)
    users_quest.save!
  end

  def send_to_user user
    users_quest = UsersQuest.new(user_id: user.id,
                                 quest_id: self.id,
                                 status: 10)
    users_quest.save!
  end

  def correct_reward?
    if !self.reward || self.reward < 0 || self.reward > 100
      false
    else
      true
    end
  end

  def completed_times
    self.users.where(users_quests: {status: 2}).count
  end
  def accepted_times
    self.users.where(users_quests: {status: 1}).count
  end
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
  def index
    @users = User.all
    @quests = Quest.all
    @users_quests = UsersQuest.all
    if current_user
      @has_new_quest = current_user.has_new_quest?
    end
  end
  def complete
    quest = Quest.find(params[:quest_id])
    quest.complete current_user

  end

  def accept
    #completing quest
    quest = Quest.find(params[:quest_id])

    ActiveRecord::Base.transaction do
      begin
        if quest.complete current_user
          flash[:success] = (t :quest_completed, scope: :flash)
        else
          flash[:alert] = (t :quest_completed_e, scope: :flash)
          raise ActiveRecord::Rollback, "completing  failed"
        end

      end
    end
    redirect_to quests_path
  end

  def delete
    #giving up quest
    quest = Quest.find(params[:quest_id])
    ActiveRecord::Base.transaction do
      begin
        if quest.give_up current_user
          flash[:success] = (t :quest_give_s, scope: :flash)
        else
          flash[:alert] = (t :quest_give_e, scope: :flash)
          raise ActiveRecord::Rollback, "giving up  failed"
        end

      end
    end
    redirect_to quests_path
  end
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/views/quests/index.html.erb
<title>QuestLife</title>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>

<!------ Include the above in your HEAD tag ---------->


<body>
<div id="navbar-wrapper">
  <header>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">QuestLife</a>
        </div>

        <div id="navbar-collapse" class="collapse navbar-collapse">
          <!--
         <form class="navbar-form navbar-left" role="search">
           <div class="input-group">
             <input type="text" class="form-control" placeholder="Search">
             <span class="input-group-btn">
                                   <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
                               </span>
           </div> -->

          </form>
          <ul class="nav navbar-nav navbar-right">
            <!--
            <li class="dropdown">
              <a id="flag" href="#" class="dropdown-toggle" data-toggle="dropdown">
                <img src="http://www.country-dialing-codes.net/img/png-country-4x2-fancy-res-1280x960/gb.png" alt="English" width="28px" height="18px">
              </a>
              <ul class="dropdown-menu dropdown-menu-flag" role="menu">
                <li>
                  <a href="#">
                    <img src="http://www.country-dialing-codes.net/img/png-country-4x2-flat-res-640x480/gf.png" alt="Français" width="28px" height="18px">
                    <span>Français</span>
                  </a>
                </li>
              </ul>
            </li> -->
            <%if current_user %>
              <li>
                <div class="name">
                  <%= current_user.name%>
                </div>
              </li>
              <li>
                <div class="lvl">
                  <%=t :lvl, scope: :menu %>: <%= current_user.level %>
                  <%=t :score, scope: :menu %>: <%=current_user.score %>
                </div>
              </li>
              <li class="dropdown">
                <%= link_to 'En', home_path(locale: :en), method: 'PATCH' %>
              </li>
              <li class="dropdown">
                <%= link_to 'Sk', home_path(locale: :sk), method: 'PATCH' %>
              </li>
              <li class="dropdown">
                <%= link_to (t :logout, scope: :menu), login_path(), method: 'DELETE' %>
              </li>

            <%else %>
              <li class="dropdown">
                <%= link_to 'En', home_path(locale: :en), method: 'PATCH' %>
              </li>
              <li class="dropdown">
                <%= link_to 'Sk', home_path(locale: :sk), method: 'PATCH' %>
              </li>
              <li>
                <h4><a href="/<%=locale%>/login"><%=t :login, scope: :menu %></a></h4>
              </li>
            <%end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>
</div>
<div id="wrapper">
  <div id="sidebar-wrapper">
    <aside id="sidebar">
      <ul id="sidemenu" class="sidebar-nav">
        <li>
          <a href="/<%=locale%>/home">
            <span class="sidebar-icon"><i class="fa fa-home"></i></span>
            <span class="sidebar-title"><%=t :home, scope: :menu %></span>
          </a>
        </li>
        <%if current_user %>
          <li>
            <a href="/<%=locale%>/new_quests">
              <span class="sidebar-icon new-quest"><i class="fa fa-exclamation-circle"></i></span>
              <%if @has_new_quest > 0 %>
                <span class="sidebar-title new-quest"><%=t :new_quests, scope: :menu %></span>
              <%else %>
                <span class="sidebar-title"><%=t :new_quests, scope: :menu %></span>
              <%end %>

            </a>
          </li>
          <li>
            <a href="/<%=locale%>/quests">
              <span class="sidebar-icon"><i class="fa fa-question-circle"></i></span>
              <span class="sidebar-title"><%=t :my_quests, scope: :menu %></span>
            </a>
          </li>
          <li>
            <a href="/<%=locale%>/created_quests">
              <span class="sidebar-icon"><i class="fa fa-database"></i></span>
              <span class="sidebar-title"><%=t :created_quests, scope: :menu %></span>
            </a>
          </li>
          <li>
            <a href="/<%=locale%>/create_quest">
              <span class="sidebar-icon"><i class="fa fa-certificate"></i></span>
              <span class="sidebar-title"><%=t :create_quest, scope: :menu %></span>
            </a>
          </li>
        <%end%>
        <li>
          <a href="/<%=locale%>/allquests">
            <span class="sidebar-icon"><i class="fa fa-clone"></i></span>
            <span class="sidebar-title"><%=t :all_quests, scope: :menu %></span>
          </a>
        </li>
        <li>
          <a href="/<%=locale%>/rooms">
            <span class="sidebar-icon"><i class="fa fa-user"></i></span>
            <span class="sidebar-title"><%=t :rooms, scope: :menu %></span>
          </a>
        </li>
        <li>
          <a href="/<%=locale%>/about">
            <span class="sidebar-icon"><i class="fa fa-info-circle"></i></span>
            <span class="sidebar-title"><%=t :about, scope: :menu %></span>
          </a>
        </li>
      </ul>
    </aside>
  </div>
  <main id="page-content-wrapper" role="main">
    <!-- stred -->
    <div class="container">
      <div class="row">
        <div class="well">
          <h1 class="text-center"><%=t :title, scope: :my_quests %></h1>
          <% flash.each do |key, value| %>

            <div class="alert alert-<%= key %>"><%= value %></div>
          <% end %>
          <% accepted = current_user.quests.where(:users_quests => {status: '1'}).order('id').paginate(page: params[:page], per_page: 7) %>
          <% accepted.each  do |quest|    %>


            <div class="list-group">
              <a href="/<%=locale%>/quest_detail?quest_id=<%=quest.id %>" class="list-group-item active">
                <div class="col-sm-9">
                  <p class="list-group-item-heading"> <%= quest.task %> </p>
                </div>

                <div class="col-sm-1">
                  <p class="list-group-item-heading"> <%=t :reward, scope: :models %>: </p>
                </div>
                <div class="col-sm-1">
                  <p class="list-group-item-heading"> <%= quest.reward %> </p>
                </div>


              </a>
              <div class="col-sm-2 ruby-button">
                <%= link_to (t :complete, scope: :my_quests), quest_accept_path(quest), method: 'POST' %>
              </div>
              <div class="col-sm-2 ruby-button">
                <%= link_to (t :give_up, scope: :my_quests), quest_delete_path(quest), method: 'DELETE' %>
              </div>
              <br>
            </div>
          <% end %>
          <%=will_paginate accepted %>
        </div>
      </div>
    </div>
  </main>
</div>
</body>